---
name: 'mkdocforge'

services:
  mkdocforge:
    container_name: mkdocforge
    image: mkdocforge:v1
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8000:8000'
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
    command: mkdocs serve --dev-addr=0.0.0.0:8000
